### POST buat user baru
POST http://localhost:5000/api/register
Content-Type: application/json

{
  "username": "abrar",
  "email": "test2ussess2rs22@example.com",
  "password": "123"
}

###

### login update user
POST http://localhost:5000/api/login
Content-Type: application/json

{
  "username": "admin4",
  "password": "bomboclat123"
}

### GET semua user
GET http://localhost:5000/api/users
Content-Type: application/json

###

### GET user by ID
GET http://localhost:5000/api/users/10
Content-Type: application/json

###

### PUT update user
PUT http://localhost:5000/api/users/1`
Content-Type: application/json

{
  "username": "admin",
  "email": "upsdaed232@example.com",
  "password": "123",
  "bb": 80,
  "tb": 180,
  "usia": 21,
  "jenis_kelamin": "Laki-laki"
}

###

### DELETE user
DELETE http://localhost:5000/api/users/10
Content-Type: application/json
